name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  gem_kit:
    path: ../plugins/gem_kit

  equatable: ^2.0.5
  image: ^4.3.0
  intl: ^0.19.0
  rxdart: ^0.27.7
  permission_handler: ^11.3.1
  geolocator: ^10.1.0
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
