name: core
description: A sample command-line application.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  gem_kit:
    path: ../plugins/gem_kit

  running_app:
    path: ../

  domain:
    path: ../domain
  data:
    path: ../data
  openapi:
    path: ../api

  shared:
    path: ../shared
  

  dio: '^5.2.0'
  get_it: ^7.6.4
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
