name: running_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gem_kit:
    path: plugins/gem_kit
  
  domain:
    path: domain
  
  core:
    path: core

  shared:
    path: shared

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  image: ^4.3.0
  dots_indicator: ^3.0.0
  another_flushbar: ^1.12.30
  
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_platform_widgets: ^7.0.1
  modal_bottom_sheet: ^3.0.0
  fluttertoast: ^8.2.8
  easy_sticky_header: ^1.1.1
  flutter_image_compress: ^2.4.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  hive_generator: ^2.0.1
  device_info_plus: ^11.3.0
  platform_info: ^5.0.0
  timeago: ^3.7.1
  fl_chart: ^0.71.0
  dotted_line: ^3.2.3
  another_xlider: ^3.0.2
  svg_flutter: ^0.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  analyzer: ^4.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/map_styles/styles/
    - assets/map_styles/previews/
    - assets/gpx_files/
