name: domain
description: A sample command-line application.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  core:
    path: ../core
  equatable: ^2.0.5
  rxdart: ^0.27.7
  dartz: ^0.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
